export const wheelConfig = {
  slots: 21,
  centerX: 400,
  spinDuration: 5000,
  spinDeceleration: 0.95,
  centerY: 400,
  outerRadius: 550,
  innerRadius: 375,
  gapWidth: 10,
  cornerRadius: 15,
  randomOffset: 8,
  prizes: [
    { image: 'bear.svg', value: '15', chance: 9 },
    { image: 'bear.svg', value: '15', chance: 9 },
    { image: 'rose.svg', value: '25', chance: 15 },
    { image: 'bust.svg', value: 'Буст', chance: 12 },
    { image: 'heart.svg', value: '15', chance: 9 },
    { image: 'flowers.svg', value: '50', chance: 8 },
    { image: 'diamond.svg', value: '100', chance: 3 },
    { image: 'gift.svg', value: '25', chance: 15 },
    { image: 'rocket.svg', value: '50', chance: 8 },
    { image: 'bear.svg', value: '15', chance: 9 },
    { image: 'heart.svg', value: '15', chance: 9 },
    { image: 'ring.svg', value: '100', chance: 3 },
    { image: 'rose.svg', value: '25', chance: 15 },
    { image: 'bust.svg', value: 'Буст', chance: 12 },
    { image: 'trophy.svg', value: '100', chance: 3 },
    { image: 'bear.svg', value: '15', chance: 9 },
    { image: 'rose.svg', value: '25', chance: 15 },
    { image: 'flowers.svg', value: '50', chance: 8 },
    { image: 'gift.svg', value: '25', chance: 15 },
    { image: 'snake.svg', value: '400', chance: 0.5 },
    { image: 'rose.svg', value: '25', chance: 15 }
  ]
};
